#!/bin/bash

if  [ -z "$1" ] || \
    [[ "$1" != "bb"  && "$1" != "core" && "$1" != "sp" ]] || \
    [ -z "$2" ] || \
    [[ "$2" != "mainnet"  && "$2" != "testnet" ]]; then
    echo "usage: scripts/create [bb|core|sp] [testnet|mainnet]"
    exit 1
fi

case "$1" in 
    "bb")
    STACK="$2-bin-build"
    ;;
    "core")
    STACK="$2-core"
    ;;
    "sp")
    STACK="$2-stake-pool"
    ;;
esac

cdk synth
cdk deploy ${STACK}